### ISSUE TITLE
钉钉小程序中真机预览报无权跨域调用

### ISSUE THREAD

**Issue by adufeng** [zjxxxxxxxxx/axios-miniprogram#45]
### 描述错误

钉钉中真机预览及上传后预览，报错，无权跨域调用，对应的接口已经在安全中心配置过了，使原生请求不会出现这个错误

### 附加上下文

<img width="900" alt="image" src="https://github.com/zjxxxxxxxxx/axios-miniprogram/assets/52154350/1031963d-eb27-4c2a-a227-00417b4238d9">

测试了使用原生请求及其他库，没有这个错误，真机可以正常预览

### 使用过的包管理器

yarn

### 验证

- [X] 遵守我们的[行为准则 ](https://github.com/zjx0905/axios-miniprogram/blob/main/CODE_OF_CONDUCT.md)
- [X] 阅读[贡献指南](https://github.com/zjx0905/axios-miniprogram/blob/main/CONTRIBUTING.md).
- [X] 阅读[文档](https://axios-miniprogram.com).
- [X] 检查是否还没有报告相同错误的[问题](https://github.com/zjx0905/axios-miniprogram/issues)以避免创建重复。
- [X] 确保这是 axios-miniprogram 问题而不是特定于框架的问题。

**Comment by zjxxxxxxxxx** [comment]
我现在遇到网络问题，无法验证这个问题。想先了解一下，这个库发出的请求和原生请求，在 network 中有何差异，比如 url，请求头，请求体或者其他。

**Comment by adufeng** [comment]
> 我现在遇到网络问题，无法验证这个问题。想先了解一下，这个库发出的请求和原生请求，在 network 中有何差异，比如 url，请求头，请求体或者其他。

可以方便加个联系方式吗？我加你看下

**Comment by zjxxxxxxxxx** [comment]
> > 我现在遇到网络问题，无法验证这个问题。想先了解一下，这个库发出的请求和原始请求，在网络中有何不同，url，请求头，请求体或者其他。
> 
> 方便可以加个联系方式吗？我加你看下

这里不方便留联系方式，邮箱联系我 954270063@qq.com
