### ISSUE TITLE
AxiosResponseData默认应该是any才对吧

### ISSUE THREAD

**Issue by lihanspace** [zjxxxxxxxxx/axios-miniprogram#46]
### 描述错误

AxiosResponseData默认应该是any才对吧
![image](https://github.com/zjxxxxxxxxx/axios-miniprogram/assets/60546798/2c044333-0a5d-414b-817c-beca335fd4e0)
在axios库中
```ts
export interface AxiosResponse<T = any, D = any> {
  data: T;
  status: number;
  statusText: string;
  headers: RawAxiosResponseHeaders | AxiosResponseHeaders;
  config: InternalAxiosRequestConfig<D>;
  request?: any;
}
```
https://github.com/axios/axios/blob/a989ccdc1a672171e9b45d3f02edc260109a607c/index.d.ts#L378

### 使用过的包管理器

npm

### 验证

- [X] 遵守我们的[行为准则 ](https://github.com/zjxxxxxxxxx/axios-miniprogram/blob/main/CODE_OF_CONDUCT.md)
- [X] 阅读[贡献指南](https://github.com/zjxxxxxxxxx/axios-miniprogram/blob/main/CONTRIBUTING.md).
- [X] 阅读[文档](https://axios-miniprogram.com).
- [X] 检查是否还没有报告相同错误的[问题](https://github.com/zjxxxxxxxxx/axios-miniprogram/issues)以避免创建重复。
- [X] 确保这是 axios-miniprogram 问题而不是特定于框架的问题。

**Comment by zjxxxxxxxxx** [comment]
> ### 描述错误
> axiosResponseData默认应该是any才对吧 在axios库中 ![图像](https://user-images.githubusercontent.com/60546798/265968481-2c044333-0a5d-414b-817c-beca335fd4e0.png)
> 
> ```ts
> export interface AxiosResponse<T = any, D = any> {
>   data: T;
>   status: number;
>   statusText: string;
>   headers: RawAxiosResponseHeaders | AxiosResponseHeaders;
>   config: InternalAxiosRequestConfig<D>;
>   request?: any;
> }
> ```
> 
> https://github.com/axios/axios/blob/a989ccdc1a672171e9b45d3f02edc260109a607c/index.d.ts#L378
> 
> ### 附加上下文
> _没有反应_
> 
> ### 使用过的包管理器
> 新项目管理
> 
> ### 验证
> * [x] 遵守我们的[行为准则](https://github.com/zjxxxxxxxxx/axios-miniprogram/blob/main/CODE_OF_CONDUCT.md)
> * [x] 阅读[贡献指南](https://github.com/zjxxxxxxxxx/axios-miniprogram/blob/main/CONTRIBUTING.md)。
> * [x] 阅读[文档](https://axios-miniprogram.com)。
> * [x] 检查是否还没有报告错误的[问题](https://github.com/zjxxxxxxxxx/axios-miniprogram/issues)广东省重复。
> * [x] 确定这是 axios-miniprogram 的问题而不是特定于框架的问题。

很高兴能够收到你的反馈。

为什么没有使用 any？

因为 axios 的类型不够严格，所以我并没有完全参考它，该库的类型定义是比 axios 更为严格的，总的来说对 axios 的类型做了补强吧。
这里不使用 any 能够更好的提醒用户，在不知道后端会返回什么样的数据时做好类型判断。
如果你知道后端会返回什样的数据，定义好类型才是更好的选择，当然也可以传入 any 泛型，忽略报错，但不太建议这样做。
另外 taro，uni-app 也都对 data 做的严格的类型定义，严格的类型限制总得来说肯定是利大于弊的，不然太容易把 `TypeScript` 写成 `AnyScript`。

**Comment by lihanspace** [comment]
好的谢谢
