### ISSUE TITLE
当上下顺序发送请求后，配置中的数据相同

### ISSUE THREAD

**Issue by gao-xiang** [zjxxxxxxxxx/axios-miniprogram#47]
### 描述错误

// 更新用户数据  
const res = await updateUser(useAuth.userInfo.uuid, data)
  useAuth.userInfo!.nickname = res.data.nickname

// 刷新用户Token
 const resToken = await refreshTokenApi(params)

发现第二个请求一直报错，检查后是在config.headers 中加上了Authorization，

但是我在请求拦截中做过了判断：
if(useAuth.token.access_token && config.url !== '/sso/sso/token') {
      config.headers['Authorization'] = `Bearer ${useAuth.token.access_token}`
 }

发现独立发送刷新Token没问题，但是和其它的同时发送，第二个刷新用户Token的请求中被带上了Authorization，导致失败。

### 使用过的包管理器

源码包（指直接下载 zip 文件的方式）

### 验证

- [X] 遵守我们的[行为准则 ](https://github.com/zjxxxxxxxxx/axios-miniprogram/blob/main/CODE_OF_CONDUCT.md)
- [X] 阅读[贡献指南](https://github.com/zjxxxxxxxxx/axios-miniprogram/blob/main/CONTRIBUTING.md).
- [X] 阅读[文档](https://axios-miniprogram.com).
- [X] 检查是否还没有报告相同错误的[问题](https://github.com/zjxxxxxxxxx/axios-miniprogram/issues)以避免创建重复。
- [X] 确保这是 axios-miniprogram 问题而不是特定于框架的问题。

**Comment by zjxxxxxxxxx** [comment]
> ### 描述错误
> // 更新用户数据 const res = await updateUser(useAuth.userInfo.uuid, data) useAuth.userInfo!.nickname = res.data.nickname
> 
> // 刷新用户Token const resToken = await refreshTokenApi(params)
> 
> 发现第二个请求一直报错，检查后是在config.headers 中加上了Authorization，
> 
> 但是我在请求拦截中做过了判断： if(useAuth.token.access_token && config.url !== '/sso/sso/token') { config.headers['Authorization'] = `Bearer ${useAuth.token.access_token}` }
> 
> 发现独立发送刷新Token没问题，但是和其它的同时发送，第二个刷新用户Token的请求中被带上了Authorization，导致失败。
> 
> ### 附加上下文
> _No response_
> 
> ### 使用过的包管理器
> 源码包（指直接下载 zip 文件的方式）
> 
> ### 验证
> * [x]  遵守我们的[行为准则 ](https://github.com/zjxxxxxxxxx/axios-miniprogram/blob/main/CODE_OF_CONDUCT.md)
> * [x]  阅读[贡献指南](https://github.com/zjxxxxxxxxx/axios-miniprogram/blob/main/CONTRIBUTING.md).
> * [x]  阅读[文档](https://axios-miniprogram.com).
> * [x]  检查是否还没有报告相同错误的[问题](https://github.com/zjxxxxxxxxx/axios-miniprogram/issues)以避免创建重复。
> * [x]  确保这是 axios-miniprogram 问题而不是特定于框架的问题。

结构赋值是否可以解决问题？

```js
 if (useAuth.token.access_token && config.url !== '/sso/sso/token') {
  config.headers = {
    ...config.headers,
    Authorization: `Bearer ${useAuth.token.access_token}`,
  };
}
```
