### ISSUE TITLE
post 无法使用formData入参

### ISSUE THREAD

**Issue by yyt-do** [zjxxxxxxxxx/axios-miniprogram#48]
### 描述错误

post 请求无法使用formData入参，参数总是为空对象

### 使用过的包管理器

npm

### 验证

- [X] 遵守我们的[行为准则 ](https://github.com/zjxxxxxxxxx/axios-miniprogram/blob/main/CODE_OF_CONDUCT.md)
- [X] 阅读[贡献指南](https://github.com/zjxxxxxxxxx/axios-miniprogram/blob/main/CONTRIBUTING.md).
- [X] 阅读[文档](https://axios-miniprogram.com).
- [X] 检查是否还没有报告相同错误的[问题](https://github.com/zjxxxxxxxxx/axios-miniprogram/issues)以避免创建重复。
- [X] 确保这是 axios-miniprogram 问题而不是特定于框架的问题。

**Comment by zjxxxxxxxxx** [comment]
我无法根据你的简要描述定位问题，我需要知道你是如何使用的，最好有代码片段可参考

**Comment by yyt-do** [comment]
就是在使用post请求时，想要使用formdata格式的数据作为参数时，只有将upload设置为true才有效果，这点和原生axios使用起来差距太大，希望你能处理下



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: zjxxxxxxxxx ***@***.***&gt;
发送时间: 2023年10月11日 22:41
收件人: zjxxxxxxxxx/axios-miniprogram ***@***.***&gt;
抄送: yyt-do ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [zjxxxxxxxxx/axios-miniprogram] post 无法使用formData入参 (Issue #48)





 
我无法根据你的简要描述定位问题，我需要知道你是如何使用的，最好有代码片段可参考

**Comment by zjxxxxxxxxx** [comment]
据我所知，小程序和浏览器存在差异，小程序 post 请求并不支持 formdata，upload 设置为 true，发送的上传文件的请求，上传文件是支持 formdata 的，不知道你是否有使用小程序原生 post 请求发送 formdata 的经验？可以告知我。

**Comment by yyt-do** [comment]
我是使用浏览器去发送post请求的，刚好后端要求使用formdata格式的，因为我看你这个包不是兼容h5吗，那肯定要在浏览器里面使用的



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: zjxxxxxxxxx ***@***.***&gt;
发送时间: 2023年10月14日 18:17
收件人: zjxxxxxxxxx/axios-miniprogram ***@***.***&gt;
抄送: yyt-do ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [zjxxxxxxxxx/axios-miniprogram] post 无法使用formData入参 (Issue #48)





 
据我所知，小程序和浏览器存在差异，小程序 post 请求并不支持 formdata，upload 设置为 true，发送的上传文件的请求，上传文件是支持 formdata 的，不知道你是否有使用小程序原生 post 请求发送 formdata 的经验？可以告知我。

**Comment by zjxxxxxxxxx** [comment]
> 我是使用浏览器去发送post请求的，刚好后端要求使用formdata格式的，因为我看你这个包不是兼容h5吗，那肯定要在浏览器里面使用的 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: zjxxxxxxxxx ***@***.***&gt; 发送时间: 2023年10月14日 18:17 收件人: zjxxxxxxxxx/axios-miniprogram ***@***.***&gt; 抄送: yyt-do ***@***.***&gt;, Author ***@***.***&gt; 主题: Re: [zjxxxxxxxxx/axios-miniprogram] post 无法使用formData入参 (Issue #48) 据我所知，小程序和浏览器存在差异，小程序 post 请求并不支持 formdata，upload 设置为 true，发送的上传文件的请求，上传文件是支持 formdata 的，不知道你是否有使用小程序原生 post 请求发送 formdata 的经验？可以告知我。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

您好，该库并不原生兼容 h5，该库的 h5 能力依托于第三方框架，由第三方框架提供，目前我无法定位问题，是能否提供最小可复现代码片段。

**Comment by zjxxxxxxxxx** [comment]
> > 我是使用浏览器去发送post请求的，刚好后端要求使用formdata格式的，因为我看你这个包不是兼容h5吗，那肯定要在浏览器里面使用的 发自我的iPhone
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: zjxxxxxxxxx _**@**_._**> 发送时间: 2023年10月14日 18:17 收件人: zjxxxxxxxxx/axios-miniprogram _**@**_.**_> 抄送: yyt-do _**@**_._**>, Author _**@**_.**_> 主题: Re: [zjxxxxxxxxx/axios-miniprogram] post 无法使用formData入参 (Issue #48) 据我所知，小程序和浏览器存在差异，小程序 post 请求并不支持 formdata，upload 设置为 true，发送的上传文件的请求，上传文件是支持 formdata 的，不知道你是否有使用小程序原生 post 请求发送 formdata 的经验？可以告知我。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: _**@**_.***>
> 
> 您好，该库并不原生兼容 h5，该库的 h5 能力依托于第三方框架，由第三方框架提供，目前我无法定位问题，是能否提供最小可复现代码片段。

另外，如果您的目标平台只有 h5，建议直接使用 axios，它是 h5 的最好方案。
