### ISSUE TITLE
上传文件名为中文时后端怎么还原?

### ISSUE THREAD

**Issue by shiyl962** [zjxxxxxxxxx/axios-miniprogram#50]
### 描述错误

如题，后端得到的是编码后的文件名，怎么还原为原文件名？通过Api调试工具测试，后端是正确的中文文件名，故排除了后端的问题。经前端跟踪排查，一直到传入axiox-miniprogram的api，文件名没有被编码，因此问题可能与axiox-miniprogram有关。请问如何解决？

### 附加上下文

采用的技术栈：vue + taro3 + wechatdevtools

### 使用过的包管理器

yarn

### 验证

- [X] 遵守我们的[行为准则 ](https://github.com/zjxxxxxxxxx/axios-miniprogram/blob/main/CODE_OF_CONDUCT.md)
- [X] 阅读[贡献指南](https://github.com/zjxxxxxxxxx/axios-miniprogram/blob/main/CONTRIBUTING.md).
- [X] 阅读[文档](https://axios-miniprogram.com).
- [X] 检查是否还没有报告相同错误的[问题](https://github.com/zjxxxxxxxxx/axios-miniprogram/issues)以避免创建重复。
- [X] 确保这是 axios-miniprogram 问题而不是特定于框架的问题。

**Comment by zjxxxxxxxxx** [comment]
您是如何使用的？

```ts
axios.post(
  '/file',
  {

    name: '中文文件名', // 这样？
    filePath: tempFilePaths[0],
  },
  {
    upload: true,
  },
);
```

```ts
axios.post(
  '/file',
  {
    restParam: '其他中文参数', // 这样？
    name: 'filename',  
    filePath: tempFilePaths[0],
  },
  {
    upload: true,
  },
);
```

**Comment by zjxxxxxxxxx** [comment]
中文 name 似乎在小程序中不被支持，后端反向解码是否能够解决问题。

**Comment by shiyl962** [comment]
谢谢回复！
不是name处用中文，是 filePath 指定的文件是中文名。
我用的是对此库的二次封装: https://github.com/wlllyfor/taro-vue3/blob/main/src/services/http.ts, 代码如下：
```
upload(url: string, data: unknown, file): Promise<AxiosResponse> | Promise<HttpResponse> {
  return this.request({
    method: 'post',
    url: url,
    upload: true,
    data: Object.assign({
        // 文件对应的 key，开发者在服务端可以通过这个 key 获取文件的二进制内容
        name: 'file',

        // 要上传文件资源的路径 (本地路径)
        filePath: file.url,
      },
      {
        // 经 axios-miniprogram 处理后，后端收到的是转码后的非中文文件名，故暂时作为参数传给后端
        fileName: file.name
      },
      data
    )
  })
}
```
后端结果：其中的 filename 经过编码的，不知道怎么还原。
<HTML>
<head>
<title></title></head>
<body>


  | Name | Value | Type
-- | -- | -- | --
  | ContentDisposition | "form-data; name=\"file\"; filename=\"3f18vGJQz6dO81648f3d98e6b13e1d556c8de2456e99.dwg\"" | string



</body>
</HTML>

![capture_20231117103820977](https://github.com/zjxxxxxxxxx/axios-miniprogram/assets/38456157/c8385297-155c-40c9-8481-54ae9c759983)

**Comment by zjxxxxxxxxx** [comment]
中文的的 file.name 怎么来的？在我的认知里，小程序获取的文件名称是一串 hash 字符，而不是原始文件名，[参见](https://developers.weixin.qq.com/community/develop/doc/00082c89688d5881299ddb46152000?highLine=%25E5%25AE%259C%25E5%2585%25B4%25E5%25AE%25BE%25E9%25A6%2586%25E5%25A6%25B9%25E5%25AD%2590%25E3%2580%2590%25E2%2592%259228%25E2%2592%2598%25E2%2592%2594%25E5%25AA%25BA%25E3%2580%2591%25E8%25A6%2581%25E4%25B9%25B1)

**Comment by zjxxxxxxxxx** [comment]
太久没做小程序开发了，看了看官方文档，原来的 wx.chooseVideo 已经被废弃了。

**Comment by shiyl962** [comment]
> 中文的 file.name 怎么来的？在我的认知里，小程序获取的文件名称是一串 hash 字符，而不是原始文件名，[参见](https://developers.weixin.qq.com/community/develop/doc/00082c89688d5881299ddb46152000?highLine=%25E5%25AE%259C%25E5%2585%25B4%25E5%25AE%25BE%25E9%25A6%2586%25E5%25A6%25B9%25E5%25AD%2590%25E3%2580%2590%25E2%2592%259228%25E2%2592%2598%25E2%2592%2594%25E5%25AA%25BA%25E3%2580%2591%25E8%25A6%2581%25E4%25B9%25B1)，使用的 [chooseMessageFile](https://developers.weixin.qq.com/miniprogram/dev/api/media/image/wx.chooseMessageFile.html)?

用的组件 https://vant-contrib.gitee.io/vant-weapp/#/uploader
经跟踪此处仍为 中文文件名，故附加了参数，后端也能正确获取 ```
 {
        // 经 axios-miniprogram 处理后，后端收到的是转码后的非中文文件名，故暂时作为参数传给后端
        fileName: file.name
      }
```

**Comment by zjxxxxxxxxx** [comment]
{
// 经 axios-miniprogram 处理后，后端收到的是转码后的非中文文件名，故暂时作为参数传给后端
fileName: file.name
}

这里 file.name 是中文，但是后端拿到的  fileName 是编码后的？

**Comment by shiyl962** [comment]
这样啊！目前可以排除后端的问题，因为用web api 调试工具测试，ContentDisposition 中是中文文件名。

由于 wechatdevtools 中看不到以formdata 方式提交的数据，不知道是哪个环节被编码的。

如果单文件上传的话，目前的用法也能用。

另外请教一下，此库能实现多文件上传吗，文档中没有看到。

再次感谢您的回复！！！

**Comment by zjxxxxxxxxx** [comment]
该库目前不支持多文件上传，同时也没有实现多文件上传的计划，该库的目标是简化使用小程序请求，抹平跨端使用差异，而不会去增强小程序偏底层的功能，因为这样会加大跨端适配的难度。
如果您特别需要多文件上传的功能，开源社区也存在一些可用的库，比如 [wx-multipar](https://github.com/supperchong/wx-multipart)。

**Comment by shiyl962** [comment]
> 该库目前不支持多文件上传，同时也没有实现多文件上传的计划，该库的目标是简化使用小程序请求，抹平跨端使用差异，而不会去增强小程序偏底层的功能，因为这样会加大跨端适配的难度。 如果您特别需要多文件上传的功能，开源社区也存在一些可用的库，比如 [wx-multipar](https://github.com/supperchong/wx-multipart)。

好的，谢谢啦！！！
