### ISSUE TITLE
能否支持最新的axios

### ISSUE THREAD

**Issue by jieruian** [zjxxxxxxxxx/axios-miniprogram#51]
### 清晰简洁的问题描述

目前responseType: "stream",的时候，不能像axios1.4.0 以后，onDownloadProgress:这个方法不走。最新的axios是走onDownloadProgress的

### 建议的解决方案

希望能支持最新的axios

### 验证

- [X] 遵守我们的[行为准则 ](https://github.com/zjxxxxxxxxx/axios-miniprogram/blob/main/CODE_OF_CONDUCT.md)
- [X] 阅读[贡献指南](https://github.com/zjxxxxxxxxx/axios-miniprogram/blob/main/CONTRIBUTING.md).
- [X] 阅读[文档](https://axios-miniprogram.com).

**Comment by zjxxxxxxxxx** [comment]
您好，我通过查阅小程序文档得知，在小程序中仅[下载文件](https://developers.weixin.qq.com/miniprogram/dev/api/network/download/DownloadTask.html)和[上传文件](https://developers.weixin.qq.com/miniprogram/dev/api/network/upload/UploadTask.html)支持监听进度变化，[普通请求](https://developers.weixin.qq.com/miniprogram/dev/api/network/request/RequestTask.html)似乎没有提供可用的方法。

**Comment by jieruian** [comment]
> 您好，通过查阅小程序文档得知，在小程序中仅[下载文件](https://developers.weixin.qq.com/miniprogram/dev/api/network/download/DownloadTask.html)和[上传文件](https://developers.weixin.qq.com/miniprogram/dev/api/network/upload/UploadTask.html)支持监听进度变化，[普通请求](https://developers.weixin.qq.com/miniprogram/dev/api/network/request/RequestTask.html)似乎并没有提供可用的方法。
> 
> 另外，我有一个没有亲自实践过，但理论上应该行得通的想法，stream 格式的数据应该是可以直接用下载文件的方式获取的，这样就可以监听进度变化了。

您好，其实这样的。我在做openAI的接口，它有一个是stream格式的数据，用的是POST请求，实现的效果就是把问题答案用流的方式下发下来的。然后我在react和vue项目上做的时候，一开始axios版本比较低，onDownloadProgress里面拿不到下发的流数据。后来我更新个axios之后，它就可以在onDownloadProgress拿到流的数据了。现在要在小程序里做这个功能，微信自带的网络请求就不支持这个格式。然后选择了在小程序里用axios。发现您这个库，能拿到最后的结果，但是onDownloadProgress不走。和我一开始没更新axios的情况一样。所以才询问是否能升级一波axios。

**Comment by zjxxxxxxxxx** [comment]
您好，该库是对小程序请求方法和上传下载的封装，一切功能都是基于小程序的接口封装而来，在小程序中还是没有办法绕开小程序本身的限制的，我们只能在小程序接口的基础之上寻找问题的解决办法，毕竟小程序环境和浏览器环境是存在区别的。您可以查阅一下该库适配器的实现，就会明白，这里没有黑魔法。

另外，我没有看见您提供代码片段，所以不清楚您是通过普通请求拿到的数据，还是通过下载文件(download:true)的请求拿到的数据，目前的情况是普通请求没有办法实现监听进度变化，不知道您是否有尝试我之前提到的方法，用下载文件的方法是否可以曲线救国。
