### ISSUE TITLE
小程序导入 执行完npm 构建 一直提示这个，Error: module 'xxx/xxx/axios-miniprogram.js' is not defined, require args is 'axios-miniprogram'

### ISSUE THREAD

**Issue by easynulls** [zjxxxxxxxxx/axios-miniprogram#52]
### 描述错误

你好，小程序导入 执行完npm 构建 一直提示这个，有遇到过吗？

### 附加上下文

[Deprecation] SharedArrayBuffer will require cross-origin isolation as of M92, around July 2021. See https://developer.chrome.com/blog/enabling-shared-array-buffer/ for more details.
[system] WeChatLib: 2.32.3 (2023.11.20 23:35:17)
Current Wechat version do not support asynchronous getSystemInfo. "wx.getSystemInfoAsync" will be finished by synchronous implementation.
[system] Subpackages: N/A
[system] LazyCodeLoading: true
Lazy code loading is enabled. Only injecting required components.
[Violation] 'setTimeout' handler took 121ms
app.js错误:
 Error: module 'kits/fetch/axios-miniprogram.js' is not defined, require args is 'axios-miniprogram'
    at q (WASubContext.js?t=wechat&s=1700653677994&v=2.32.3:1)
    at n (WASubContext.js?t=wechat&s=1700653677994&v=2.32.3:1)
    at index.js?t=wechat&s=1700653677994&v=4fb5352f9f01f60d2620d908a5650988:34
    at WASubContext.js?t=wechat&s=1700653677994&v=2.32.3:1
    at f.runWith (WASubContext.js?t=wechat&s=1700653677994&v=2.32.3:1)
    at q (WASubContext.js?t=wechat&s=1700653677994&v=2.32.3:1)
    at n (WASubContext.js?t=wechat&s=1700653677994&v=2.32.3:1)
    at index.js?t=wechat&s=1700653677994&v=22cf6a6c86864f33957ae69f55a37b33:24
    at WASubContext.js?t=wechat&s=1700653677994&v=2.32.3:1
    at f.runWith (WASubContext.js?t=wechat&s=1700653677994&v=2.32.3:1)(env: macOS,mp,1.06.2310080; lib: 2.32.3)
Error: module 'kits/fetch/axios-miniprogram.js' is not defined, require args is 'axios-miniprogram'
    at q (WASubContext.js?t=wechat&s=1700653677994&v=2.32.3:1)
    at n (WASubContext.js?t=wechat&s=1700653677994&v=2.32.3:1)
    at index.js?t=wechat&s=1700653677994&v=4fb5352f9f01f60d2620d908a5650988:34
    at WASubContext.js?t=wechat&s=1700653677994&v=2.32.3:1
    at f.runWith (WASubContext.js?t=wechat&s=1700653677994&v=2.32.3:1)
    at q (WASubContext.js?t=wechat&s=1700653677994&v=2.32.3:1)
    at n (WASubContext.js?t=wechat&s=1700653677994&v=2.32.3:1)
    at index.js?t=wechat&s=1700653677994&v=22cf6a6c86864f33957ae69f55a37b33:24
    at WASubContext.js?t=wechat&s=1700653677994&v=2.32.3:1
    at f.runWith (WASubContext.js?t=wechat&s=1700653677994&v=2.32.3:1)(env: macOS,mp,1.06.2310080; lib: 2.32.3)
Page "pages/index/index" has not been registered yet.
[system] Launch Time: 6725 ms

### 使用过的包管理器

yarn

### 验证

- [X] 遵守我们的[行为准则 ](https://github.com/zjxxxxxxxxx/axios-miniprogram/blob/main/CODE_OF_CONDUCT.md)
- [X] 阅读[贡献指南](https://github.com/zjxxxxxxxxx/axios-miniprogram/blob/main/CONTRIBUTING.md).
- [X] 阅读[文档](https://axios-miniprogram.com).
- [X] 检查是否还没有报告相同错误的[问题](https://github.com/zjxxxxxxxxx/axios-miniprogram/issues)以避免创建重复。
- [X] 确保这是 axios-miniprogram 问题而不是特定于框架的问题。

**Comment by easynulls** [comment]
> 目前没有遇见，这可能和模块类型有一定关系，能否提供最小代码片段用于复现问题。

可以 https://github.com/easynulls/miniprogram-typescript-starter

**Comment by zjxxxxxxxxx** [comment]
根据提供的代码，运行后发现产物中并不包含 'axios-miniprogram' 相关代码，所以判断是构建本身的问题，和该库无关。

为了验证这个问题，我又尝试安装 'lodash'，最终得到相同的结果，这是构建本身的问题，外部依赖库被忽略掉了。

![WX20231123-093012@2x](https://github.com/zjxxxxxxxxx/axios-miniprogram/assets/43126836/d1af86ab-d997-4af4-b69c-a0f1b430eda9)

**Comment by easynulls** [comment]
> 根据提供的代码，运行后发现产物中并不包含 'axios-miniprogram' 相关代码，所以判断是构建本身的问题，和该库无关。
> 
> 为了验证我的猜想，我又尝试安装 'lodash'，最终得到相同的结果，这是构建本身的问题，外部依赖库被忽略掉了。
> 
> ![WX20231123-093012@2x](https://github.com/zjxxxxxxxxx/axios-miniprogram/assets/43126836/d1af86ab-d997-4af4-b69c-a0f1b430eda9)
> 

谢谢，我研究一下，

**Comment by easynulls** [comment]
> > 根据提供的代码，运行后发现产物中并不包含 'axios-miniprogram' 相关代码，所以判断是构建本身的问题，和该库无关。
> > 为了验证我的猜想，我又尝试安装 'lodash'，最终得到相同的结果，这是构建本身的问题，外部依赖库被忽略掉了。
> > ![WX20231123-093012@2x](https://user-images.githubusercontent.com/43126836/285078546-d1af86ab-d997-4af4-b69c-a0f1b430eda9.png)
> 
> 谢谢，我研究一下，

感谢指点，是我的esbuild脚本不完善导致的，因为看了小程序官方文档那些提问，被带偏了哈，谢谢作者的指点
