### ISSUE TITLE
文件上传乱码与返回格式问题

### ISSUE THREAD

**Issue by easynulls** [zjxxxxxxxxx/axios-miniprogram#53]
### 描述错误

1. 上传文件返回值出现乱码现象
<img width="975" alt="image" src="https://github.com/zjxxxxxxxxx/axios-miniprogram/assets/132973069/35125d4c-87b7-4357-83a9-f8b4e8e2ea9e">
2. 上传成功后的data没有被序列化成json

![image](https://github.com/zjxxxxxxxxx/axios-miniprogram/assets/132973069/f702cc2a-8485-43ee-a87b-6eababe9489a)

### 附加上下文

<img width="563" alt="image" src="https://github.com/zjxxxxxxxxx/axios-miniprogram/assets/132973069/94fb696e-db7a-4785-9fe8-0d98f73fef5c">

### 使用过的包管理器

yarn

### 验证

- [X] 遵守我们的[行为准则 ](https://github.com/zjxxxxxxxxx/axios-miniprogram/blob/main/CODE_OF_CONDUCT.md)
- [X] 阅读[贡献指南](https://github.com/zjxxxxxxxxx/axios-miniprogram/blob/main/CONTRIBUTING.md).
- [X] 阅读[文档](https://axios-miniprogram.com).
- [X] 检查是否还没有报告相同错误的[问题](https://github.com/zjxxxxxxxxx/axios-miniprogram/issues)以避免创建重复。
- [X] 确保这是 axios-miniprogram 问题而不是特定于框架的问题。

**Comment by easynulls** [comment]
怀疑过是服务端问题，把数据放mock 服务中一样存在该问题

**Comment by zjxxxxxxxxx** [comment]
这种问题非常常见，一般和使用的编码有很大关系，中文需要使用 `utf-8`。
