### ISSUE TITLE
请求拦截器中，修改header会导致全局变化

### ISSUE THREAD

**Issue by lihanspace** [zjxxxxxxxxx/axios-miniprogram#55]
### 描述错误

比如我在拦截器中添加token，token会被固定在header中，除非我手动删除掉token `delete config.headers.token`，否则token就一直存在

### 使用过的包管理器

npm

### 验证

- [x] 遵守我们的[行为准则 ](https://github.com/zjxxxxxxxxx/axios-miniprogram/blob/main/CODE_OF_CONDUCT.md)
- [X] 阅读[贡献指南](https://github.com/zjxxxxxxxxx/axios-miniprogram/blob/main/CONTRIBUTING.md).
- [X] 阅读[文档](https://axios-miniprogram.com).
- [X] 检查是否还没有报告相同错误的[问题](https://github.com/zjxxxxxxxxx/axios-miniprogram/issues)以避免创建重复。
- [X] 确保这是 axios-miniprogram 问题而不是特定于框架的问题。

**Comment by zjxxxxxxxxx** [comment]
感谢反馈该问题，我已经找到了出现这个问题的原因，你可以使用解构赋值临时解决此问题。
