### ISSUE TITLE
原生微信小程序 解决 module 'utils/axios-miniprogram.js' is not defined, require args is 'axios-miniprogram' 

### ISSUE THREAD

**Issue by yanglei9999** [zjxxxxxxxxx/axios-miniprogram#57]
### 描述错误

原生微信小程序
参考文档用
npm install -D axios-miniprogram
安装, 再用 [微信开发者工具] -> [工具]-> [构建 npm]
报错 : module 'utils/axios-miniprogram.js' is not defined, require args is 'axios-miniprogram' 
小程序根目录中的 miniprogram_npm 目录,也没有 axios-miniprogram 文件夹,说明小程序 构建npm 这步, 没有执行成功, 所以才会报错

解决方案: npm install axios-miniprogram 把命令改成这个就可以了.  

### 附加上下文

![image](https://github.com/zjxxxxxxxxx/axios-miniprogram/assets/5676213/8db15077-ed65-41ef-8737-64179997c967)

### 使用过的包管理器

npm

### 验证

- [X] 遵守我们的[行为准则 ](https://github.com/zjxxxxxxxxx/axios-miniprogram/blob/main/CODE_OF_CONDUCT.md)
- [X] 阅读[贡献指南](https://github.com/zjxxxxxxxxx/axios-miniprogram/blob/main/CONTRIBUTING.md).
- [X] 阅读[文档](https://axios-miniprogram.com).
- [X] 检查是否还没有报告相同错误的[问题](https://github.com/zjxxxxxxxxx/axios-miniprogram/issues)以避免创建重复。
- [X] 确保这是 axios-miniprogram 问题而不是特定于框架的问题。

**Comment by zjxxxxxxxxx** [comment]
感谢指出问题，是文档写错了。
