### ISSUE TITLE
咨询一下底层请求方法

### ISSUE THREAD

**Issue by freshBirdA** [zjxxxxxxxxx/axios-miniprogram#60]
### 描述错误

我在飞书小程序项目中hook了tt.request方法进行劫持，但是发现使用axios发出的请求无法被我hook的tt.request劫持到。但是我看源码其实原理也是用tt.request去发请求的，所以想请问一下为什么？
代码如下
`export const RequestWithPerformanceReport = ({
  reportClient,
}: {
  reportClient: any;
}) => {
  if (!tt || !tt.request) return;

  const originttRequest = tt.request;

  tt.request = (options: any) => {
    console.log("options:", options)
    originttRequest(options);
  };
};
`

### 使用过的包管理器

npm

### 验证

- [X] 遵守我们的[行为准则 ](https://github.com/zjxxxxxxxxx/axios-miniprogram/blob/main/CODE_OF_CONDUCT.md)
- [X] 阅读[贡献指南](https://github.com/zjxxxxxxxxx/axios-miniprogram/blob/main/CONTRIBUTING.md).
- [X] 阅读[文档](https://axios-miniprogram.com).
- [X] 检查是否还没有报告相同错误的[问题](https://github.com/zjxxxxxxxxx/axios-miniprogram/issues)以避免创建重复。
- [X] 确保这是 axios-miniprogram 问题而不是特定于框架的问题。

**Comment by zjxxxxxxxxx** [comment]
猜测和执行顺序有关，可以尝试在hook后进行手动适配，看看能不能解决问题。

**Comment by freshBirdA** [comment]
> 猜测和执行顺序有关，可以尝试在hook后进行手动适配，看看能不能解决问题。

所以底层应该还是用的tt.request吧(飞书的容器下)，另外请问下你说的手动适配是要怎么做呢

**Comment by zjxxxxxxxxx** [comment]
可以参考[适配方法](https://axios-miniprogram.com/advanced/adapter)

```js
import axios from 'axios-miniprogram';
// 需要确保在hook之后执行
axios.defaults.adapter = axios.createAdapter(tt);
```

**Comment by freshBirdA** [comment]
> 可以参考[适配方法](https://axios-miniprogram.com/advanced/adapter)
> 
> ```js
> import axios from 'axios-miniprogram';
> // 需要确保在hook之后执行
> axios.defaults.adapter = axios.createAdapter(tt);
> ```

感谢，好像确实有用，不过需要这样写才行，否则会报错
<img width="330" alt="image" src="https://github.com/zjxxxxxxxxx/axios-miniprogram/assets/65576620/2c0cf03d-a24e-4f80-a313-70ceba8e77f6">
